version: "3.9"
services:
  website:
    image: homeca_django_test:${version}
    deploy:
      replicas: 3
    restart: always
    ports:
      - "8000"
    networks:
        - global
    depends_on:
        - homeca-django-db
        - homeca-minio
        - redis
        - rabbitmq

  nginx:
    image: nginx:latest
    volumes:
      - ./etc/load-balancer.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - website
    networks:
      - global
    ports:
      - "9004:80"

  website-upgrade:
    image: homeca_django_test:${version}
    restart: always
    ports:
      - "9008:8000"
    networks:
        - global
    depends_on:
        - homeca-django-db
        - homeca-minio
        - redis
        - rabbitmq

  homeca-django-db:
    image: mysql:5.7
    restart: always
    networks:
      - global
    volumes:
      - /root/homeca/DB:/var/lib/mysql
      - /root/homeca/backups:/var/backups

  redis:
    image: webhippie/redis:latest
    restart: always
    environment:
      - REDIS_DATABASES=1
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - redis:/var/lib/redis
    networks:
      - global
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    volumes:
        - rabbit-etc:/etc/rabbitmq/
        - rabbit-data:/var/lib/rabbitmq/
        - rabbit-log:/var/log/rabbitmq
      
  homeca-minio:
    image: minio/minio
    restart: always
    volumes: 
      - '/root/homeca/minio-data:/data'
    command: server /data

volumes:
  redis:
  rabbit-etc:
  rabbit-data:
  rabbit-log:


  
